defaults: &defaults
  environment:
    - DEPENDENCIES_BASE_URL: "https://raw.githubusercontent.com/wireapp/wire-ios-shared-resources/master"
  macos:
    xcode: "10.0.0"
  shell: /bin/bash --login -eo pipefail

# ----------------CACHING----------------

# Gems
gems_cache: &gems_cache
  key: v4-{{ checksum "Gemfile.lock" }}
  paths: ~/.gem

# Carthage
carthage_cache: &carthage_cache
  key: v2-{{ checksum "Cartfile.resolved" }}
  paths: Carthage/Build

# -------------GEMS----------------

version: 2
jobs:
      
  build:
    <<: *defaults
    branches:
      ignore:
        - develop
    steps:
    - checkout
    - run: 
        name: "Setup gems"
        command: |
          curl -O "${DEPENDENCIES_BASE_URL}/Gemfile"
          curl -O "${DEPENDENCIES_BASE_URL}/Gemfile.lock"
          curl -O "${DEPENDENCIES_BASE_URL}/.ruby-version"
    - restore_cache: *gems_cache
    - restore_cache: *carthage_cache
    - run: 
        name: "Install gems"
        command: bundle install --path ~/.gem
    - run: 
        name: "Build"
        command: bundle exec fastlane build
    - run: 
        name: "Test"
        command: bundle exec fastlane test
    - run: 
        name: "Post test"
        command: bundle exec fastlane post_test
    - store_test_results:
        path: test

